import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { resetConfigCache } from '@goodvibes/core/config';
import { addLimitClause, classifyStatement, isReadOnlyQuery } from '../db/query-analysis.js';
import * as registry from '../fetch/service-registry.js';
import { loadSecrets, saveSecrets } from '../fetch/secrets-store.js';
import { handleDbQuery } from '../tools/db-query.js';

interface ParsedEnvelope {
  success: boolean;
  error?: string;
}

async function call(args: unknown): Promise<ParsedEnvelope> {
  const result = await handleDbQuery(args);
  const block = (result.content as Array<{ type: string; text: string }>)[0];
  return JSON.parse(block.text) as ParsedEnvelope;
}

describe('SQL classifier adversarial cases', () => {
  it.each([
    ['SHOW TABLES', 'SHOW'],
    ['DESCRIBE users', 'DESCRIBE'],
    ['DECLARE cursor_name CURSOR FOR SELECT 1', 'DECLARE'],
    ['FETCH ALL FROM cursor_name', 'FETCH'],
  ])('rejects unknown statement class %s', (sql, verb) => {
    const result = classifyStatement(sql);
    expect(result.allowed).toBe(false);
    expect(result.kind).toBe('unknown');
    expect(result.reason).toContain(verb);
  });

  it.each([
    'SELECT 1; SELECT 2',
    'SELECT 1; -- comment cannot hide the second statement\nDELETE FROM users',
    'SELECT 1; /* nested /* comment */ still ends */ UPDATE users SET admin = true',
  ])('rejects stacked SQL: %s', sql => {
    expect(classifyStatement(sql)).toMatchObject({ allowed: false, kind: 'unknown' });
    expect(classifyStatement(sql).reason).toMatch(/multiple|stacked/i);
  });

  it('ignores semicolons and dangerous words inside comments and quoted values', () => {
    const sql =
      "/* DELETE FROM secrets; */ SELECT '; DROP TABLE users' AS harmless -- UPDATE users";
    expect(classifyStatement(sql)).toMatchObject({ allowed: true, kind: 'read' });
  });

  it.each([
    ['CALL rotate_keys()', 'CALL'],
    ['DO $$ BEGIN DELETE FROM users; END $$', 'DO'],
    ["COPY users TO PROGRAM 'sh -c id'", 'COPY'],
    ['EXEC dangerous_procedure', 'EXEC'],
    ['EXECUTE dangerous_procedure', 'EXECUTE'],
    ['SET ROLE administrator', 'SET'],
    ['EXPLAIN ANALYZE SELECT * FROM users', 'ANALYZE'],
    ['ANALYZE users', 'ANALYZE'],
    ["ATTACH DATABASE '/tmp/other.db' AS other", 'ATTACH'],
    ['PRAGMA journal_mode = WAL', 'PRAGMA'],
    ['PRAGMA writable_schema(ON)', 'PRAGMA'],
    ["COPY (SELECT * FROM users) TO '/tmp/users'", 'COPY'],
  ])('rejects unsupported control or unsafe statement %s', (sql, verb) => {
    const result = classifyStatement(sql);
    expect(result.allowed).toBe(false);
    expect(result.kind).toBe('unknown');
    expect(result.reason).toContain(verb);
  });

  it.each(['PRAGMA table_info(users)', 'PRAGMA index_list(users)', 'PRAGMA compile_options'])(
    'allows explicitly enumerated read-only PRAGMA %s',
    sql => {
      expect(classifyStatement(sql)).toMatchObject({ allowed: true, kind: 'read' });
    }
  );

  it.each([
    'WITH changed AS (DELETE FROM users RETURNING *) SELECT * FROM changed',
    'WITH source AS (SELECT 1) INSERT INTO audit_log DEFAULT VALUES',
    'WITH source AS (SELECT 1) UPDATE users SET admin = true',
  ])('classifies a data-modifying CTE as a write: %s', sql => {
    expect(classifyStatement(sql)).toMatchObject({ allowed: true, kind: 'write' });
    expect(isReadOnlyQuery(sql)).toBe(false);
  });

  it('classifies a read-only CTE as a read', () => {
    expect(classifyStatement('WITH one AS (SELECT 1 AS n) SELECT n FROM one')).toMatchObject({
      allowed: true,
      kind: 'read',
    });
  });

  it('does not let a leading comment bypass the automatic SELECT limit', () => {
    const sql = '/* request generated by client */ SELECT * FROM users';
    expect(addLimitClause(sql, 100)).toBe(`${sql} LIMIT 100`);
  });
});

describe('db_query adversarial input boundary', () => {
  let tmpDir: string;
  let originalDataRoot: string | undefined;

  beforeEach(async () => {
    tmpDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'db-query-security-'));
    originalDataRoot = process.env.GOODVIBES_DATA_ROOT;
    process.env.GOODVIBES_DATA_ROOT = path.join(tmpDir, '.goodvibes');
    await fs.promises.mkdir(process.env.GOODVIBES_DATA_ROOT, { recursive: true });
    await fs.promises.writeFile(
      path.join(process.env.GOODVIBES_DATA_ROOT, 'config.json'),
      JSON.stringify({ mode: 'restricted' })
    );
    resetConfigCache();
  });

  afterEach(async () => {
    resetConfigCache();
    if (originalDataRoot === undefined) {
      delete process.env.GOODVIBES_DATA_ROOT;
    } else {
      process.env.GOODVIBES_DATA_ROOT = originalDataRoot;
    }
    await fs.promises.rm(tmpDir, { recursive: true, force: true });
  });

  async function registerMemoryConnection(name = 'memory'): Promise<void> {
    const ref = `connection:${name}`;
    const secrets = await loadSecrets();
    secrets.global[ref] = ':memory:';
    await saveSecrets(secrets);
    await registry.addConnection(name, { secret_ref: ref });
  }

  it.each([
    { database_url: 'sqlite::memory:' },
    { url: 'sqlite::memory:' },
    { url_env: 'DATABASE_URL' },
    { connection_url: 'sqlite::memory:' },
  ])('accepts only an opaque registered connection handle, not $database_url', async extra => {
    const result = await call({ ...extra, query: 'SELECT 1' });
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/registered `connection`/i);
  });

  it('does not resolve an arbitrary inherited $env connection secret', async () => {
    process.env.ATTACKER_DATABASE_URL = ':memory:';
    try {
      await saveSecrets({
        services: {},
        global: { 'connection:legacy': { $env: 'ATTACKER_DATABASE_URL' } },
      });
      await registry.addConnection('legacy', { secret_ref: 'connection:legacy' });

      const result = await call({ connection: 'legacy', query: 'SELECT 1' });
      expect(result.success).toBe(false);
      expect(result.error).toMatch(/no readable credential handle/i);
    } finally {
      delete process.env.ATTACKER_DATABASE_URL;
    }
  });

  it.each([-1, 0, 1001, 1.5, Number.MAX_SAFE_INTEGER])(
    'rejects unsafe row limit %s',
    async limit => {
      await registerMemoryConnection();
      const result = await call({ connection: 'memory', query: 'SELECT 1', limit });
      expect(result.success).toBe(false);
      expect(result.error).toMatch(/integer from 1 through 1000/i);
    }
  );

  it('rejects an oversized SQL statement before resolving a connection', async () => {
    const result = await call({ query: `SELECT '${'x'.repeat(256_001)}'` });
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/256 KiB input limit/i);
  });

  it('rejects an oversized parameter array before resolving a connection', async () => {
    const result = await call({
      query: 'SELECT 1',
      params: Array.from({ length: 10_001 }, () => null),
    });
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/at most 10,000/i);
  });
});
